- hosts: localhost
  vars_files:
    - credentials.yml
    - variables.yml

  vars:
    vmtags:
      - "wb1"
      - "wb2"
      - "wb3"
      - "LB"

  tasks:
          - name: Launching four  instances on AWS Cloud
            ec2:
                    key_name: "{{ aws_key_pair }}"
                    instance_type: "{{ aws_instance_type }}"
                    image: "{{ aws_image }}"
                    wait: yes
                    #count: 3
                    vpc_subnet_id: "{{ aws_subnet_id }}"
                    assign_public_ip: yes
                    region: "{{ aws_region }}"
                    state: present
                    group: "{{ aws_SG }}"
                    aws_access_key: "{{ awsuser }}"
                    aws_secret_key: "{{ awspass }}"
                    instance_tags:
                            Name: "{{ item }}"
            loop: "{{ vmtags }}"
