---
# tasks file for loadbalancer


- name: Install HAPROXY package
  package:
    name: "haproxy"
    state: present

- name: Copy haproxy conf to target IP
  template: 
    src: "haproxy.cfg"
    dest: "/etc/haproxy/haproxy.cfg"
  notify: restart haproxy


- name: Start HAPROXY Service
  service:
    name: "haproxy"
    state: started
